# Generated by Django 4.2.21 on 2025-05-30 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='booking.bookingstatus'),
        ),
    ]
