# Generated by Django 4.2.21 on 2025-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_reservation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='smoking',
            field=models.BooleanField(default=False),
        ),
    ]
